### ISSUE TITLE
can't use advanced partitioning on manjaro-xfce-0.8.13-dev-x86_64

### ISSUE THREAD

**Issue by ggf84** [manjaro/thus#10]
Hello,

I'm a Ubuntu user and I've found Manjaro a few weeks ago and after some testing I've decided to abandon Ubuntu in favour of Manjaro :-D

Right now I'm trying to install manjaro-xfce-0.8.13-dev-x86_64 using the graphical installer, but when I select advanced partitioning nothing show up here. I've checked the ISO image and burned it on an usb stick according to the instructions on the wiki, and all seems fine... I've no tried to use the cli-installer, though.

Can you confirm if this is a bug?

thanks!

**Comment by Kirek** [comment]
Thanks for reporting.
Confirmed and fixed with https://github.com/manjaro/thus/commit/a30adb75b429f25ebac7a10912b53e12d61e0b03
