### ISSUE TITLE
[process] fix umount order on final step

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/thus#18]
<pre>umount: /install: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
[2015-04-12 23:43:27] [process] ERROR: Command '['umount', '/install']' returned non-zero exit status 32</pre>

**Comment by philmmanjaro** [comment]
With thus 0.8.12.100 we have now more info:
<pre>[2015-04-17 07:16:11] [chroot] DEBUG: Unmounting special dir '/install/sys'
[2015-04-17 07:16:11] [chroot] DEBUG: Unmounting special dir '/install/proc'
[2015-04-17 07:16:11] [chroot] DEBUG: Unmounting special dir '/install/dev/pts'
[2015-04-17 07:16:11] [chroot] DEBUG: Unmounting special dir '/install/dev'
umount: /install/dev: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
[2015-04-17 07:16:11] [chroot] DEBUG: Can't unmount. Try -l to force it.
umount: /install: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
[2015-04-17 07:16:13] [process] ERROR: Command '['umount', '/install']' returned non-zero exit status 32</pre>

We have to check if some other folder is still mounted on **/install/dev** ...

**Comment by Kirek** [comment]
With this should be fixed.
https://github.com/manjaro/thus/commit/cebb65019733e0cac9a6946c0b14a4f11193c0e2

**Comment by philmmanjaro** [comment]
Seems there are still some processes using **/install/dev**. We might need to check which are those with **lsof** to find a proper solution:
<pre>[2015-04-19 09:32:45] [chroot] DEBUG: Unmounting special dir '/install/sys'
[2015-04-19 09:32:45] [chroot] DEBUG: Unmounting special dir '/install/proc'
[2015-04-19 09:32:45] [chroot] DEBUG: Unmounting special dir '/install/dev/pts'
[2015-04-19 09:32:45] [chroot] DEBUG: Unmounting special dir '/install/dev'
umount: /install/dev: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
[2015-04-19 09:32:45] [chroot] DEBUG: Can't unmount. Try -l to force it.
[2015-04-19 09:32:45] [process] DEBUG: Paths to unmount: ['/source', '/source_desktop', '/install/home', '/install/boot', '/install']
[2015-04-19 09:32:45] [process] DEBUG: Unmounting /source
[2015-04-19 09:32:46] [process] DEBUG: Unmounting /source_desktop
[2015-04-19 09:32:47] [process] DEBUG: Unmounting /install/home
[2015-04-19 09:32:47] [process] DEBUG: Unmounting /install/boot
[2015-04-19 09:32:47] [process] DEBUG: Unmounting /install
umount: /install: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
[2015-04-19 09:32:47] [process] DEBUG: Can't unmount. Try -l to force it.</pre>

However using the -l switch umounts it after all:

<pre>[manjaro@manjaro Desktop]$ mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sys on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
dev on /dev type devtmpfs (rw,nosuid,relatime,size=1018600k,nr_inodes=254650,mode=755)
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
union on / type aufs (rw,relatime,si=ce5bbc094b628f26)
/dev/sr0 on /bootmnt type iso9660 (ro,noatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/bfqio type cgroup (rw,nosuid,nodev,noexec,relatime,bfqio)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=32,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw)
mqueue on /dev/mqueue type mqueue (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
tmpfs on /etc/pacman.d/gnupg type tmpfs (rw,relatime,mode=755)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=205408k,mode=700,uid=1000,gid=100)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
tmpfs on /run/user/620 type tmpfs (rw,nosuid,nodev,relatime,size=205408k,mode=700,uid=620,gid=620)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=100)</pre>

**Comment by Kirek** [comment]
Not sure its needed, in calamares we just call "umount -lv dir" and we are done with it...

**Comment by philmmanjaro** [comment]
Ok, then we forget about it here also ...
