### ISSUE TITLE
[systemd] may have made thus unusable

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/thus#21]
[systemd](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150413/003119.html) may have made **thus** unusable ...

Today I created a new install media, based on current unstable branch, to find out, that **thus** is package-wise broken. Followed [diff](https://gist.github.com/philmmanjaro/4579112a8c399fd735fa) changed usablility of **thus**.

Problem is **FileCopyThread**, which unpacks our squashed images uncorrectly on todays build. However if I use current git-code of **thus** and try to install with yesterdays install-media, all went [fine](https://gist.github.com/philmmanjaro/a8b49b06a900cd9300ad). Using all current packages will [fail](https://gist.github.com/philmmanjaro/fbb1dff39a2fd23c5559) ...

**Comment by philmmanjaro** [comment]
Using **rsync** on yesterdays install media results in:
<pre>[2015-04-20 21:37:36] [slides] INFO: Installing using the 'automatic' method
[2015-04-20 21:37:36] [slides] INFO: Indexing files of root-image to be copied ...
[2015-04-20 21:37:36] [slides] INFO: Indexing files of desktop-image to be copied ...
[2015-04-20 21:37:36] [slides] INFO: Extracting root-image ...
[2015-04-20 21:39:16] [slides] INFO: Extracting desktop-image ...
[2015-04-20 21:41:37] [chroot] DEBUG: Mounting special dir '/dev' to /install/dev</pre>

Using **rsync** on todays install media results in:
<pre>[2015-04-20 21:28:06] [slides] INFO: Installing using the 'automatic' method
[2015-04-20 21:28:06] [slides] INFO: Indexing files of root-image to be copied ...
[2015-04-20 21:28:06] [slides] INFO: Indexing files of desktop-image to be copied ...
[2015-04-20 21:28:06] [slides] INFO: Extracting root-image ...
[2015-04-20 21:29:20] [slides] INFO: Extracting desktop-image ...
[2015-04-20 21:29:20] [chroot] DEBUG: Mounting special dir '/dev' to /install/dev</pre>

extracting **root-image** in under one minute can't be. Also not 0 seconds for **desktop-image** ...

**Comment by Kirek** [comment]
I'm building an iso against unstable now.

**Comment by Kirek** [comment]
It seems in fact that is systemd fault. The source squashfs is unmounted automatically.
Reading the 219 changelog:
A .device unit for an optical block device will now be
          considered active only when a medium is in the drive. Also,
          mount units are now bound to their backing devices thus
          triggering automatic unmounting when devices become
          unavailable. With this in place systemd will now
          automatically unmount left-over mounts when a CD-ROM is
          ejected or an USB stick is yanked from the system.

This bug report seems somewhat related https://bugzilla.redhat.com/show_bug.cgi?id=1196417
We need to try this reverting this commit http://cgit.freedesktop.org/systemd/systemd/commit/?id=06e97888883e2cc12eb6514e80c7f0014295f59b

**Comment by Kirek** [comment]
It seems that this patches solves it too:
http://cgit.freedesktop.org/systemd/systemd/commit/src/core/mount.c?id=628c89cc68ab96fce2de7ebba5933725d147aecc

**Comment by Kirek** [comment]
Uploaded patched systemd https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150420/003127.html, please test

**Comment by philmmanjaro** [comment]
Great @Kirek, will test it later. I knew it was **systemd** ...

**Comment by philmmanjaro** [comment]
Yep works now.
