### ISSUE TITLE
Thus throws errors about the rpmb partition

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/thus#22]
Since the kernel supports now mmc Thus throws errors about the rpmb partition. Nevertheless the installation is successful.

![error](https://cloud.githubusercontent.com/assets/959709/7336863/81d8e61c-ec11-11e4-8796-faff55311f20.jpg)
![log](https://cloud.githubusercontent.com/assets/959709/7336864/81d95dd6-ec11-11e4-9147-307de156b03a.jpg)

**Comment by philmmanjaro** [comment]
first try: e1b1937915770f1bf979eeb7b434358ad4d07a41
second try: 744e69c13bd3cb00a6f5ae5522c98c360fc68417

**Comment by philmmanjaro** [comment]
Testcode:
<pre>#!/usr/bin/python

import re

DEVICE_BLACKLIST = ["^mtd", r'^mmcblk.+boot', r'^mmcblk.+rpmb', "^zram"]

aList = ['/dev/mmcblk0', '/dev/mmcblk0rpmb', '/dev/mmcblk0boot0']

print("List : {}".format(aList))

for dev in aList:
    dev_name = dev[5:]
    if any(re.search(expr, dev_name) for expr in DEVICE_BLACKLIST):
        continue
    print("device : {}".format(dev))</pre>
Result:
<pre>python ./run.py
List : ['/dev/mmcblk0', '/dev/mmcblk0rpmb', '/dev/mmcblk0boot0']
device : /dev/mmcblk0
</pre>

**Comment by vincent-t** [comment]
Thus 0.8.12.106-2 fixed the problem. Thank you very much.
