### ISSUE TITLE
MMC - Thus creates wrong mount options in fstab

### ISSUE THREAD

**Issue by vincent-t** [manjaro/thus#23]
MMC is flash memory therefore the mount options should be ```defaults,rw,noatime,discard``` instead of ```defaults,rw,relatime,data=ordered```.

**Comment by Kirek** [comment]
What's the value of "/sys/block/DISK_NAME/queue/rotational" ?
Also would be useful the ouput of "hdparm -I /dev/DISK_NAME"
Thanks

**Comment by vincent-t** [comment]
```
cat /sys/block/mmcblk0/queue/rotational 0
```

```
sudo hdparm -I /dev/mmcblk0

/dev/mmcblk0:
 HDIO_DRIVE_CMD(identify) failed: Invalid argument
```

**Comment by Kirek** [comment]
In the installed system there should be a file called /var/log/thus-DATE.log can you upload it somewhere?

**Comment by vincent-t** [comment]
Here is the log: http://pastebin.com/GGEGYf0q

**Comment by philmmanjaro** [comment]
Well, we should add a check for **/dev/mmcblk** or **/dev/mmc** to detect those. Also this is a new feature we just added recently. We are the first supporting it. I'm sure we will find a proper solution for it.

**Comment by Kirek** [comment]
The check is the same but I guess we pass the wrong disk path (something NOT /dev/mmcblk0)
The log its unhelpful because thus wasn't started without the -d and -v flags (we need to fix that, users shouldn't need to start thus with special flags so we can get useful logs).

**Comment by philmmanjaro** [comment]
@vincent-t: please use latest thus version. Either redownload our install media our use update function of thus with:
<pre>thus -dvu</pre>
You need active internet connection for that. To give a proper development log please use:
<pre>thus -dv</pre>
Also post the content of **/etc/fstab** from your installed system. Your posted log seems to use an outdated thus version. See also my [changelog](http://sourceforge.net/projects/manjarotest/files/0.8.13/xfce-minimal/0.8.13-dev/manjaro-xfce-0.8.13-dev-x86_64-change.log).

@Kirek: might think about it. For normal results current way should be enough. Here we are working on a new requested function. Currently we have only this code:
<pre>            # Add mount options parameters
            if not is_ssd:
                if "btrfs" in myfmt:
                    opts = 'defaults,rw,relatime,space_cache,autodefrag,inode_cache'
                elif "f2fs" in myfmt:
                    opts = 'defaults,rw,noatime'
                elif "ext3" in myfmt or "ext4" in myfmt:
                    opts = 'defaults,rw,relatime,data=ordered'
                else:
                    opts = "defaults,rw,relatime"
            else:
                # As of linux kernel version 3.7, the following
                # filesystems support TRIM: ext4, btrfs, JFS, and XFS.
                if myfmt == 'ext4' or myfmt == 'jfs' or myfmt == 'xfs':
                    opts = 'defaults,rw,noatime,discard'
                elif myfmt == 'btrfs':
                    opts = 'defaults,rw,noatime,compress=lzo,ssd,discard,space_cache,autodefrag,inode_cache'
                else:
                    opts = 'defaults,rw,noatime'</pre>

This out, the user can currently only get the wanted result by using advanced mode and marking his MMC card as SSD drive. We have no autodetect in **Thus** yet ...

**Comment by philmmanjaro** [comment]
I took another quick look: to properly fix this, we have to write an routine to detect MMC cards. Also these SSD flag function is only available in Advanced mode by selecting it manually. We have no autodetection yet.

**Comment by Kirek** [comment]
My guess is that /dev/mmcblk0p1 got cut to /dev/mmcblk0p, so Thus didn't find that partition, and configured fstab for a rotational disk. https://github.com/manjaro/thus/commit/8232d63088ec52907c8888930f809105434e278d should fix this.
@vincent-t 
I'm closing this, if you reinstall you system and the problem persist, just reopen this issue.

**Comment by philmmanjaro** [comment]
I uploaded a new install media for testing:
[0.8.12.201-2 (May 08 20:37)](http://sourceforge.net/projects/manjarotest/files/0.8.13/xfce-minimal/0.8.13-dev/manjaro-xfce-0.8.13-dev-x86_64-change.log)
[download iso-image](http://sourceforge.net/projects/manjarotest/files/0.8.13/xfce-minimal/0.8.13-dev/manjaro-xfce-0.8.13-dev-x86_64.iso)
[install log](https://gist.github.com/philmmanjaro/781204835e48fa48e042)
