### ISSUE TITLE
Separate volume for /home during automated install

### ISSUE THREAD

**Issue by itys** [manjaro/thus#26]
Hello:

The automated installation provides the option for a separate partition for /home which is great!  In multi-drive scenarios, having the ability to put /home on a separate volume (disk) than the install disk would be a great addition. 

This gives several benefits, two off of the top of my head is that future upgrades don't run the risk of blowing away user home directories (they get tetchy when that happens) and it allows for the use of slower spinning disks for /home while keeping SSD's for boot and root. 

I attempted to do this setup with the manual/advanced installation however LUKS had issues with formatting both / and /home, still need to dive into that a bit more. 

Thanks for considering the addition.

**Comment by philmmanjaro** [comment]
@itys: you might know that this installer is based on [Cnchi](https://github.com/Antergos/Cnchi). However, all our development goes now into our new installer [Calamares](https://github.com/calamares). This you can see with our [dev-builds](http://sourceforge.net/projects/manjarotest/files/0.9.0/xfce-minimal/0.9.0-dev/). We know that **Thus** is in a better shape regarding partitioning features than **Calamares**, but we hope to adapt to those by end of this year. Feel free to change and modify **Thus**. Any new addition of features to this installer we review and implement after passing our testing rounds.

**Comment by itys** [comment]
Happy to help with the installer. To reiterate you're looking for input to go into Thus not Calamares? 

Also, I have a bug for the dev-build. I did try to fire up build 223 (manjaro-xfce-minimal-0.9.0-dev-x86_64.iso) and working through the various kernel options and free vs non-free drivers it looks like the Nvidia GeForce GTX 280M compatible drivers aren't loading and give the characteristic black scree. I'll break down the installer and take a closer look in a VM vs. on metal.
