### ISSUE TITLE
reboot options under Openrc

### ISSUE THREAD

**Issue by oberon2007** [manjaro/thus#29]
Unfortunately the Openrc version of reboot does not accept the options `--no-wall` or `--force`
It will have to be `reboot -f`

**Comment by oberon2007** [comment]
This is working now! :) Thank you.

**Comment by philmmanjaro** [comment]
no problem. shipped with **thus-0.9.0-2**

**Comment by oberon2007** [comment]
Yes, that's the one I just tried ... :D
