### ISSUE TITLE
Additional condition for adding resume hook

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/thus#31]
Would it be possible to check if mkinitcpio has systemd hook, and not add resume hook if it does? This would allow using systemd hook instead of base, udev, usr and fsck hooks in respins, even if swap partition is created on installation.

**Comment by Chrysostomus** [comment]
This would also require using sd-encrypt instead of encrypt and sd-lvm2 instead of lvm2 if sysremd hook is present.

**Comment by philmmanjaro** [comment]
I don't get your question here. Be more specific why we should drop resume.

**Comment by Chrysostomus** [comment]
systemd hook provides its own resume mechanism. Having both systemd hook and resume hook gives errors on boot. In effect, systemd hook replaces base, udev, usr and resume hooks. 

I don't think resume should be dropped altogether, but giving it additional condition would allow using systemd hook in custom iso profiles.

**Comment by Chrysostomus** [comment]
More details about use of systemd hook are covered here: https://bbs.archlinux.org/viewtopic.php?pid=1480241

**Comment by philmmanjaro** [comment]
Remember that we also support **OpenRC** so this is not so simple to do. We first have to check if we want to go with the **systemd hook** for **systemd**. Then we have to modify several applications, including **Thus**. I'll take a look at it when I find time.

**Comment by Chrysostomus** [comment]
Yeah, I figured it might be difficult to implement while supporting two initsystems. Going with normal hooks is no doubt better and more maintanence effective choice. 

I thought that thus modified some existing /etc/mkinitcpio.conf file, so that I could make changes to it in my manjaro-tools iso profile. But based on what you write, it seems that it chooses some preconfigured files based on situation.

I don't necessarily advocate changing default hooks for systemd isos. I thought it was something that could be configured separately for different iso profiles (it would be neat to do in bspwm respin). But if it causes much trouble and messes with other maintainers work, it probably is not worth it.

But if mkinitcpio can be configured separately for different iso profiles, then cool :)
