### ISSUE TITLE
GRUB2 unable to boot XFS root partion

### ISSUE THREAD

**Issue by geckolinux** [manjaro/thus#32]
I just tried installing Manjaro 15.09 on a Thinkpad T530 with MSDOS partioning scheme on a Samsung 840 PRO SSD, in a single /dev/sda1 partition formatted as XFS. GRUB2 is unable to boot the system, with errors of

`not correct XFS inode`
`attempt to read or write outside of partition`

I also tried a separate /boot partition formatted as EXT4, which also failed, but in a different way. It doesn't show any errors or even the GRUB2 rescue console, it just loops to POST over and over again.

These are the related bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=1202804
https://bugzilla.redhat.com/show_bug.cgi?id=1001279
https://bugzilla.kernel.org/show_bug.cgi?id=101421
https://wiki.archlinux.org/index.php/XFS#Integrity

This bug does not exist on Ubuntu or openSUSE, which can be installed on a single XFS partition with no separate root.

**Comment by philmmanjaro** [comment]
Did you tried the [Calamares](https://calamares.io) installer, which is also shipped with this install media yet? We mostly tested **Thus** on ext filesystem. I assume at least our **cli-installer** should be able to install with **xfs** if I remember correctly.

**Comment by sb56637** [comment]
Yep, I tried Calamares, Thus, and CLI.

**Comment by philmmanjaro** [comment]
Hmm. Let me try some in VirtualBox in that regard ...

**Comment by sb56637** [comment]
I just tried the Manjaro NET install ISO in VirtualBox and got the same error. It seems to be some problem systemic in nature.

![screenshot_2015-10-09_13-39-25](https://cloud.githubusercontent.com/assets/2692138/10402608/010482dc-6e8c-11e5-89a9-2a6cd678d3e4.png)

**Comment by sb56637** [comment]
I just tried another fresh VirtualBox install to an XFS root with the Syslinux bootloader, and the bootloader failed to install, complaining of a missing `/boot`.

**Comment by sb56637** [comment]
**Update:** I managed to get Manjaro installed on XFS, but with some caveats:

I tried manually formatting a partition with `mkfs.xfs -m crc=0,finobt=0` and then installing to it with Thus or Calamares using the no-format option and setting the partition as `/`, but it still doesn't work.

What did work for me was creating a separate `/boot` partition formatted as EXT4, and then creating a secondary XFS partition as `/`. However *the default Thus and Calamares XFS formatting does not work*, and it requires manually pre-formatting the XFS partition with `mkfs.xfs -m crc=0,finobt=0`.

So, it looks like Manjaro could do two things:

1. Package and use `grub-git` from the AUR, which is supposed to support the new XFS v5 according to [this](https://wiki.archlinux.org/index.php/XFS)
1. Warn users that for the moment install to a single XFS root partition won't work
1. When formatting a partition as XFS via Thus or Calamares, the XFS options `crc=0,finobt=0` should be used.

Thanks!

**Comment by philmmanjaro** [comment]
Using a new **grub** version might create other issues. We have to find a **working** snapshot. I might evaluate a newer snapshot within the package **grub-dev** soon.

**Comment by sb56637** [comment]
Thanks @philmmanjaro 

Two more related links:

- [Here](https://calamares.io/bugs/browse/CAL-263?focusedCommentId=11309&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-11309)
- [Here](https://calamares.io/bugs/browse/CAL-273?focusedCommentId=11408&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-11408)

**Comment by philmmanjaro** [comment]
Thx for the extra information. Please open also an issue at [Calamares](https://calamares.io/bugs/) so it can be also tracked upstream. Almost [Capella daily builds](https://forum.manjaro.org/index.php?topic=27167.0) are also good for testing new features of **Calamares** ...

**Comment by sb56637** [comment]
Thanks, I did open a Calamares issue but they marked it as "not our problem":
https://calamares.io/bugs/browse/CAL-273

**Comment by philmmanjaro** [comment]
I'll keep this bug open for now. It is fixed by downgrading xfsprogs to 3.2.2.

**Comment by sb56637** [comment]
So will xfsprogs be downgraded in Manjaro?

**Comment by philmmanjaro** [comment]
What do you [think](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20151012/004569.html) ?!?

**Comment by sb56637** [comment]
> What do you think ?!?

Frankly I think that was quite a rude answer. I had no idea that packages could be retroactively downgraded in Manjaro.

**Comment by philmmanjaro** [comment]
I'm sorry if that came out that way for you, but it was [already clearly mentioned](https://github.com/manjaro/packages-core/commit/9af79487197c60a76e14f14f1794686796ad790f) how we fixed it. It will hit our **stable** branch after the regular testings ...

**Comment by sb56637** [comment]
Cool, thanks Phil. So how will the downgrade be handled by pacman when this gets pushed out, since pacman normally only upgrades, not downgrades? Will it require manual intervention?

**Comment by philmmanjaro** [comment]
Pacman will **upgrade** to the downgraded version as with any other package it will normally do. That is why we use **epochs** in our **PKGBUILDs**.

**Comment by philmmanjaro** [comment]
Reopen this issue if it is still there ...
