### ISSUE TITLE
Thus Installer in Manjaro KDE don't recognize swap partition

### ISSUE THREAD

**Issue by filipe-marques** [manjaro/thus#4]
Thus Installer in Manjaro KDE don't recognize swap partition when is installing the operating system.
I was installing Manjaro KDE 0.8.11 in a already done partition and I put to format and install the partition I wanted to put / for root and put the other partition to format as swap. The installation goes very well and at the end I restart the pc and when I was work with system I note in the system monitor that the swap was not mounted and activated. I try to activate the swap partition, but every time I restart the pc the os don't recognize the swap.

Hey by the way I have a program called Check Hash that is GUI wrapper around GNU Coreutils sha1sum. This is ideal for newbies of Manjaro. I want this program in Manjaro.
I send an email to @philmmanjaro and I wait response about that.

**Comment by philmmanjaro** [comment]
Was this issue still present within 0.8.12 release?

**Comment by filipe-marques** [comment]
I did not test it.

**Comment by philmmanjaro** [comment]
Then reopen it when it is still there ...
