### ISSUE TITLE
implement path query for existing 15.12 ISOs

### ISSUE THREAD

**Issue by oberon2007** [manjaro/thus#45]
In case someone updates the system in the live environment before installing, the recent change of drivers path will break video-driver installation.
Can we not simply query if either **/opt/live** or **/opt/livecd** exists on the ISO and mount the correct one?

**Comment by philmmanjaro** [comment]
Normally it is not recommended to do so. However you got a point there. We can also create a symlink if **/opt/live** was not found. This can be done in the install script of each PKGBUILD.

**Comment by philmmanjaro** [comment]
However, thus supports also updating the installer only and then there it is broken ...
