### ISSUE TITLE
thus stops searching for additional desktops when it finds gnome shell

### ISSUE THREAD

**Issue by coffeeking** [manjaro/thus#48]
I've noticed this bug when releasing our latest sonar image. If you select "login automatically" during installation, since we install gdm which pulls in parts of gnome shell you end up in a stripped down gnome environment without the control center. Philip Mooler from Manjaro  says it's because thus stops searching for other desktops once it finds gnome shell.

**Comment by philmmanjaro** [comment]
@coffeeking: please start **thus** with `sudo thus -dvu` and tell me if **v0.9.4.3** fixes the issue for you.

**Comment by Kirek** [comment]
https://github.com/manjaro/thus/commit/4b6aee16c01613f542064e3f1bc78e2e8f9ecbe6 should fix this

**Comment by Kirek** [comment]
Tested that https://github.com/manjaro/thus/commit/bb74f1d4398628d6a9fc2576c118c0c2f93f0772 finally fix this, @coffeeking can you confirm?

**Comment by coffeeking** [comment]
hi
Testing now. Sorry for the delay, had to burn another flash drive. I'll
reply back with my answer.
Thanks
Kendell clark


Ramon Buldó wrote:

**Comment by coffeeking** [comment]
hi
Yes, worked like a charm. Thank you for all your help, that one was a
toughy. One minor note however. I couldn't find the log either in /tmp,
/var/log, or /var/tmp, so if it hadn't I wouldn't have known where to
find the log to send to you. But it's fixed. Thank you again for that fix.
Thanks
Kendell Clark


Ramon Buldó wrote:

**Comment by Kirek** [comment]
No problem. I think it copies the log in /var/log/thus-*.log in the installed system, maybe the log in /tmp gets automatically deleted. Closing this.
