### ISSUE TITLE
Use /boot even for GRUB

### ISSUE THREAD

**Issue by mirh** [manjaro/thus#51]
I read the whole systemd/systemd#1124, and I still can't understand why somebody should ever want to mount *boot* partition to /boot/efi

So.. couldn't the partition procedure be streamlined with just **/boot** option? Should GRUB2 be the bootloader of choice it should just be a matter of passing `--efi-directory` [argument](https://wiki.gentoo.org/wiki/GRUB2#UEFI_with_GPT).

**Comment by Kirek** [comment]
Thus is mostly in maintenance mode and we will only make changes to fix bugs, so I won't change the current behaviour.

**Comment by mirh** [comment]
Oh.. why that?
Are you planning to switch or merge completely with calamares? Or what?

**Comment by Kirek** [comment]
Yes, we are planning to move to calamares, but there are some features of thus witch calamares lacks (encrypted disk), that's why we still keep it.

**Comment by mirh** [comment]
Oh, what a pity. I liked quite more thus "compact" interface. 

I hope newer calamares versions at least include systemd-boot then.
