### ISSUE TITLE
Google search for "manjaro" says "This site may be hacked." for top result "manjaro.org"

### ISSUE THREAD

**Issue by H4tch** [manjaro/thus#6]
Maybe because it redirects to "majaro.github.io"?
Anyways, here's there support page:
https://support.google.com/websearch/answer/190597?p=ws_hacked&rd=1

**Comment by philmmanjaro** [comment]
This is no issue regarding Thus. Anyway, our Wordpress-Page got hacked so we took it down. To get our webpage accessable I created a index.php with a redirect to our github.io page. Google indexed our page as hacked. We now have manjaro.org directly redirected to github.io at .org. Currently we are working on our new page and will update manjaro.org as soon as we have it finished. We will also use a new server for our new page. As our forum has some issues a new installation will fix it. Wiki and other services will be copied. Read more [here](https://manjaro.github.io/manjaro.org-broken/) and [here](https://manjaro.github.io/manjaro.org-redesigned/).
